mdn:
  continuous:
    learning_rate: 
      type: float
      range: [0.001, 0.01]
      search: log

  discrete:
    hidden_dim:
      - 16
    num_gaussians:
      - 2
    output_dim:
      - 1

  static:
    epochs: 500


