mdn:
  continuous:
    learning_rate: 
      type: float
      range: [0.001, 0.01]
      search: log
    hidden_dim:
      type: int
      range: [4, 16]
      search: linear
    num_hidden_layers:
      type: int
      range: [1, 4]
      search: linear
    num_gaussians:
      type: int
      range: [1, 8]
      search: linear
  static:
    epochs: 200
    output_dim: 1

